### ISSUE TITLE
Add missing VinylPlayOn() function to the docs

### ISSUE THREAD

**Issue by kburkhart84** [JujuAdams/Vinyl#113]
Support for emitters (including the mention of BorkBork) is in the docs, but the function VinylPlayOn() is not there.

**Comment by JujuAdams** [comment]
Needed a version bump to 6.1.0 technically ... oops.

**Comment by JujuAdams** [comment]
https://github.com/JujuAdams/Vinyl/commit/4a9b87c487ec418f3a68482a191a52750c25fce2
