### ISSUE TITLE
VinylBPMGet() & VinylBeatCountGet() return the wrong result

### ISSUE THREAD

**Issue by patchuby** [JujuAdams/Vinyl#69]
Need to change __bpmPulse with __bpmBeatCounter in the __BPMBeatCountGet function :

![image](https://github.com/JujuAdams/Vinyl/assets/9586594/0b44cc00-bf52-4751-a49a-510449a28a81)

Need to change __PersistentGet with __BPMGet in the VinylBPMGet function :

![image](https://github.com/JujuAdams/Vinyl/assets/9586594/5b05c3fc-5e25-4a5a-82ce-b0af992e2143)

**Comment by JujuAdams** [comment]
https://github.com/JujuAdams/Vinyl/commit/8bceb62224993569d374618a8a1ea96ed1149ccb
