### ISSUE TITLE
A shuffle pattern nested in a queue pattern acts like a queue

### ISSUE THREAD

**Issue by patchuby** [JujuAdams/Vinyl#70]
![image](https://github.com/JujuAdams/Vinyl/assets/9586594/ae4a4e56-9e72-47a5-902e-4bf27ccdce03)

And it will also start with the second asset in the shuffle pattern.

so testHLT goes head0 then loop1,2,3,4,5,6 then loop1,2...

**Comment by JujuAdams** [comment]
https://github.com/JujuAdams/Vinyl/commit/612fef2d885bb98e8c187648b6f10f8844d06cbd
