### ISSUE TITLE
Ability to delay Vinyl actions

### ISSUE THREAD

**Issue by patchuby** [JujuAdams/Vinyl#72]
Being able to delay the execution of functions without using an external library.

Possible ways to do this :  

- optional arguments in existing functions
- delayed copy of each function (for exemple VinylGainTargetSetDelayed)
- a single function that sets all further action on a voice or label to be delayed by a specified amount. Maybe with an option to reset with the next delayed function call

**Comment by JujuAdams** [comment]
What's your use case?

**Comment by patchuby** [comment]
I started thinking about it when making HLT (that would be solved with #73 ) to play the tail. But in general it would be useful to be able to delay action to be triggered on the next beat or the next bar. In that context a callback function that triggers on the next beat or next bar would do as well.

**Comment by JujuAdams** [comment]
No longer in scope for Vinyl native. Perhaps https://github.com/Gizmo199/audio-tempo/ could be modified to support this?

**Comment by Gizmo199** [comment]
> No longer in scope for Vinyl native. Perhaps https://github.com/Gizmo199/audio-tempo/ could be modified to support this?

Yes, this functionality is already available via `audio_tempo_queue_sound/method()`. But a `queue_delay_for(number of downbeats)` could be nice as well.

Thanks! :)
