### ISSUE TITLE
Have an "head-loop-tail" pattern type

### ISSUE THREAD

**Issue by patchuby** [JujuAdams/Vinyl#73]
Would be defined with an array containing 3 arrays for each of the head, loop and tail assets. 
Head & tail would be optional, would be defined by an empty array (or 0 ?)
Could have a "stopType" property that defines the behavior when the pattern is stopped: 
- 0 : tail is played immediately after stopping
- 1 : pattern stops without playing tail
- 2 : waits for the current loop to end before playing the tail
- 3 : waits for the next beat before stopping the current loop and playing the tail

Maybe also a blend option, would be useful if the pattern is stopped without playing a tail, or stopped before reaching the end of the head.

**Comment by JujuAdams** [comment]
Not going to implement the specific stop types, but runtime queues solve this use case.
