### ISSUE TITLE
A basic pattern played on an emitter won't have his effect chain applied

### ISSUE THREAD

**Issue by patchuby** [JujuAdams/Vinyl#78]
I've only tested this on a basic pattern might be affecting other patterns as well.
Using VinylPlay on the same pattern will apply the effects correctly.

<img width="226" alt="image" src="https://github.com/JujuAdams/Vinyl/assets/9586594/7c44e5e4-ba5a-407e-9387-08717865fdb8">

**Comment by JujuAdams** [comment]
This is intended behaviour, but it's bad intended behaviour. I'll need to work around GameMaker's limitations to get this to work.

**Comment by JujuAdams** [comment]
Effect chain manipulation no longer supported natively.
